// 奥特曼数据集
const ultramanData = [
    {
        id: 1,
        name: "初代奥特曼",
        nameEn: "Ultraman",
        era: "showa",
        year: 1966,
        height: "40m",
        weight: "3万5千吨",
        home: "M78星云光之国",
        humanHost: "早田进",
        color: "#FF1744",
        colorSecondary: "#C0C0C0",
        icon: "🔴",
        image: "images/ultraman_01.jpg",
        transformItem: "贝塔魔棒",
        timeLimit: "3分钟",
        description: "奥特曼系列的第一位主人公，来自M78星云的宇宙警备队成员。在追踪怪兽百慕拉来到地球时，与科学特搜队队员早田进合二为一。初代奥特曼开创了特摄英雄的新纪元，其标志性的斯派修姆光线成为系列的象征。",
        skills: ["斯派修姆光线", "八分光轮", "奥特攻击光线", "碎裂光线", "奥特水流"],
        stats: { power: 75, speed: 70, technique: 80, defense: 70, energy: 85, intelligence: 75 },
        rating: 4.5
    },
    {
        id: 2,
        name: "赛文奥特曼",
        nameEn: "Ultra Seven",
        era: "showa",
        year: 1967,
        height: "40m",
        weight: "3万5千吨",
        home: "M78星云光之国",
        humanHost: "诸星弹",
        color: "#FF6D00",
        colorSecondary: "#E0E0E0",
        icon: "🟠",
        image: "images/ultraman_02.jpg",
        transformItem: "奥特眼镜",
        timeLimit: "无（随地球环境变化）",
        description: "原本是M78星云的恒星观测员340号，被地球人的勇气打动而自愿留在地球保护人类。赛文奥特曼是系列中最具人气的角色之一，以头上的艾梅利姆光线和投掷出的 Eye Slugger 头镖为标志性武器，其剧集深度探讨了许多社会议题。",
        skills: ["艾梅利姆光线", "头镖（Eye Slugger）", "赛文飞镖", "奥特冲锋", "胶囊怪兽召唤"],
        stats: { power: 80, speed: 75, technique: 90, defense: 75, energy: 80, intelligence: 90 },
        rating: 5
    },
    {
        id: 3,
        name: "杰克奥特曼",
        nameEn: "Ultraman Jack",
        era: "showa",
        year: 1971,
        height: "40m",
        weight: "3万5千吨",
        home: "M78星云光之国",
        humanHost: "乡秀树",
        color: "#2979FF",
        colorSecondary: "#E0E0E0",
        icon: "🔵",
        image: "images/ultraman_03.jpg",
        transformItem: "奥特手镯",
        timeLimit: "3分钟",
        description: "在乡秀树为救小孩牺牲后，杰克与其合为一体。他的奥特手镯可以根据战斗需要变形成各种武器，是最早引入武器概念的奥特曼之一。杰克奥特曼的战斗风格灵活多变，手镯的变形能力使他能够应对各种类型的敌人。",
        skills: ["斯派修姆光线", "奥特手镯", "奥特飓风", "奥特闪光", "手镯长矛"],
        stats: { power: 78, speed: 72, technique: 82, defense: 72, energy: 82, intelligence: 78 },
        rating: 4
    },
    {
        id: 4,
        name: "艾斯奥特曼",
        nameEn: "Ultraman Ace",
        era: "showa",
        year: 1972,
        height: "40m",
        weight: "4万5千吨",
        home: "M78星云光之国",
        humanHost: "北斗星司 / 南夕子",
        color: "#00E5FF",
        colorSecondary: "#FF1744",
        icon: "💎",
        image: "images/ultraman_04.jpg",
        transformItem: "奥特戒指",
        timeLimit: "3分钟",
        description: "奥特兄弟中排名第五，是奥特之父和奥特之母的养子。艾斯奥特曼是系列中首位由男女双人合体变身的奥特曼，拥有极其丰富的光线技能，被誉为'光线王'。其梅塔利姆光线威力巨大，斩击技能更是种类繁多。",
        skills: ["梅塔利姆光线", "奥特断头刀", "宇宙五重光", "奥特圆盘刃", "艾斯之刃"],
        stats: { power: 82, speed: 68, technique: 92, defense: 68, energy: 90, intelligence: 76 },
        rating: 4.5
    },
    {
        id: 5,
        name: "泰罗奥特曼",
        nameEn: "Ultraman Taro",
        era: "showa",
        year: 1973,
        height: "53m",
        weight: "5万5千吨",
        home: "M78星云光之国",
        humanHost: "东光太郎",
        color: "#FF1744",
        colorSecondary: "#E0E0E0",
        icon: "🔥",
        image: "images/ultraman_05.jpg",
        transformItem: "奥特徽章",
        timeLimit: "3分钟",
        description: "奥特之父与奥特之母的亲生儿子，奥特兄弟中排名第六。泰罗是奥特兄弟中拥有最强战斗力的成员，也是宇宙警备队的总教官。他的斯特利姆光线吸收了奥特兄弟的能量后威力倍增，是昭和系中最强大的战士之一。",
        skills: ["斯特利姆光线", "奥特炸弹", "泰罗飓风", "奥特双重光", "新斯特利姆光线"],
        stats: { power: 88, speed: 74, technique: 85, defense: 80, energy: 88, intelligence: 80 },
        rating: 4.5
    },
    {
        id: 6,
        name: "雷欧奥特曼",
        nameEn: "Ultraman Leo",
        era: "showa",
        year: 1974,
        height: "52m",
        weight: "4万8千吨",
        home: "L77星云狮子座",
        humanHost: "凤源",
        color: "#FF1744",
        colorSecondary: "#FFD600",
        icon: "🦁",
        image: "images/ultraman_06.jpg",
        transformItem: "狮子之瞳",
        timeLimit: "2分40秒",
        description: "来自L77星云的宇宙人，故乡被马格马星人毁灭。雷欧并非光之国出身，因此没有光线技能，但以其惊人的格斗能力和武术技巧弥补了不足。在赛文的指导下不断修炼成长，是最具'修炼'主题的奥特曼，故事风格深沉悲壮。",
        skills: ["雷欧飞踢", "雷欧闪光", "能量光球", "雷欧拳击", "奥特双重闪光（与阿斯特拉）"],
        stats: { power: 92, speed: 88, technique: 78, defense: 72, energy: 68, intelligence: 80 },
        rating: 5
    },
    {
        id: 7,
        name: "迪迦奥特曼",
        nameEn: "Ultraman Tiga",
        era: "heisei",
        year: 1996,
        height: "53m",
        weight: "4万4千吨",
        home: "超古代地球",
        humanHost: "真角大古",
        color: "#2979FF",
        colorSecondary: "#FF1744",
        icon: "⚡",
        image: "images/ultraman_07.jpg",
        transformItem: "神光棒",
        timeLimit: "3分钟",
        description: "三千万年前守护地球的超古代光之巨人，因人类的选择而苏醒。迪迦是平成系列的开创者，也是中国观众最熟悉的奥特曼之一。他可以自由切换三种形态——复合型、强力型和空中型，是系列中首位引入形态切换概念的角色。",
        skills: ["哉佩利敖光线", "迪迦冷冻光线", "兰帕尔特光弹", "奥特固定光线", "瞬间移动"],
        stats: { power: 82, speed: 80, technique: 88, defense: 76, energy: 86, intelligence: 85 },
        rating: 5
    },
    {
        id: 8,
        name: "戴拿奥特曼",
        nameEn: "Ultraman Dyna",
        era: "heisei",
        year: 1997,
        height: "55m",
        weight: "5万吨",
        home: "未知（光之国系）",
        humanHost: "飞鸟信",
        color: "#2979FF",
        colorSecondary: "#FF6D00",
        icon: "💫",
        image: "images/ultraman_08.jpg",
        transformItem: "闪光剑",
        timeLimit: "3分钟",
        description: "迪迦奥特曼七年后出现的年轻战士，人间体飞鸟信是TPC宇宙开发局的新人。戴拿拥有闪光型、强壮型和奇迹型三种形态，其中奇迹型拥有操控空间的能力。他的故事延续了迪迦的世界观，探讨了人类面对未知的勇气。",
        skills: ["索尔捷特光线", "加尔奈特轰炸", "立波留姆光波", "闪亮光刃", "奇迹空间斩"],
        stats: { power: 80, speed: 82, technique: 85, defense: 74, energy: 84, intelligence: 82 },
        rating: 4.5
    },
    {
        id: 9,
        name: "盖亚奥特曼",
        nameEn: "Ultraman Gaia",
        era: "heisei",
        year: 1998,
        height: "50m",
        weight: "4万2千吨",
        home: "地球",
        humanHost: "高山我梦",
        color: "#FF1744",
        colorSecondary: "#000000",
        icon: "🌍",
        image: "images/ultraman_09.jpg",
        transformItem: "蓝宝锥",
        timeLimit: "无限制（地球内）",
        description: "由地球本身意志诞生的光之巨人，代表大地的力量。与来自宇宙的阿古茹奥特曼形成对立与共存的关系。盖亚可以变身为至高型，与阿古茹联手对抗根源性灭亡体。他的故事深刻探讨了地球保护与人类发展的矛盾。",
        skills: ["量子流线", "盖亚突击光线", "至高型·闪光之刃", "盖亚斩击", "净化光波"],
        stats: { power: 86, speed: 76, technique: 84, defense: 82, energy: 88, intelligence: 86 },
        rating: 4.5
    },
    {
        id: 10,
        name: "奈克瑟斯奥特曼",
        nameEn: "Ultraman Nexus",
        era: "heisei",
        year: 2004,
        height: "49m",
        weight: "4万吨",
        home: "未知",
        humanHost: "真木舜一 / 姬矢准 / 千树怜 / 孤门一辉",
        color: "#AA00FF",
        colorSecondary: "#E0E0E0",
        icon: "🔮",
        image: "images/ultraman_10.jpg",
        transformItem: "进化信赖者",
        timeLimit: "依形态变化",
        description: "最黑暗深沉的奥特曼作品，讲述了适能者们在暗处与异生兽战斗的故事。奈克瑟斯拥有幼年、青年、蓝色青年和诺亚四种形态，其世界观设定深远影响了后续作品。黑暗扎基与诺亚的对决是系列中最宏大的战斗之一。",
        skills: ["十字光线·风暴", "粒子羽翼", "重叠光线·风暴", "诺亚·无限光线", "诺亚·银河"],
        stats: { power: 88, speed: 82, technique: 92, defense: 78, energy: 95, intelligence: 88 },
        rating: 5
    },
    {
        id: 11,
        name: "梦比优斯奥特曼",
        nameEn: "Ultraman Mebius",
        era: "heisei",
        year: 2006,
        height: "49m",
        weight: "3万5千吨",
        home: "M78星云光之国",
        humanHost: "未来",
        color: "#FF1744",
        colorSecondary: "#AA00FF",
        icon: "🌟",
        image: "images/ultraman_11.jpg",
        transformItem: "梦比优斯气息",
        timeLimit: "3分钟",
        description: "奥特之父派遣到地球的最年轻宇宙警备队成员，是奥特兄弟精神的继承者。梦比优斯可以变身为勇者形态和无限形态，无限形态更是融合了奥特六兄弟的力量。本作是昭和奥特曼40周年纪念作品，充满了怀旧与感动。",
        skills: ["梦比姆光线", "梦比姆光剑", "梦比姆炸弹", "无限光线", "梦比优斯凤凰"],
        stats: { power: 80, speed: 78, technique: 82, defense: 76, energy: 84, intelligence: 78 },
        rating: 4.5
    },
    {
        id: 12,
        name: "赛罗奥特曼",
        nameEn: "Ultraman Zero",
        era: "heisei",
        year: 2009,
        height: "49m",
        weight: "3万5千吨",
        home: "M78星云光之国",
        humanHost: "岚 / 大河望",
        color: "#2979FF",
        colorSecondary: "#FF1744",
        icon: "⚔️",
        image: "images/ultraman_12.jpg",
        transformItem: "赛罗眼镜",
        timeLimit: "3分钟",
        description: "赛文奥特曼之子，因年轻气盛触碰等离子火花被罚在K76星修炼，后成为拯救光之国的英雄。赛罗拥有多种形态——常态、月神奇迹型、强壮日冕型、闪耀赛罗、超限赛罗和终极赛罗。他是新生代奥特曼的领路人，人气极高。",
        skills: ["赛罗双重射线", "艾梅利姆切割", "赛罗飞踢", "终极赛罗之剑", "赛罗奥特曼光辉"],
        stats: { power: 90, speed: 86, technique: 88, defense: 82, energy: 92, intelligence: 84 },
        rating: 5
    },
    {
        id: 13,
        name: "银河奥特曼",
        nameEn: "Ultraman Ginga",
        era: "new-gen",
        year: 2013,
        height: "不定（通常20m~40m）",
        weight: "不定",
        home: "未来宇宙",
        humanHost: "礼堂光",
        color: "#FF1744",
        colorSecondary: "#2979FF",
        icon: "🌌",
        image: "images/ultraman_13.jpg",
        transformItem: "银河火花",
        timeLimit: "3分钟",
        description: "来自未来的光之战士，与礼堂光合为一体对抗黑暗火花造成的怪兽祸患。银河奥特曼可以自由调整身体大小，并与维克特利奥特曼合体为银河维克特利。他是新生代奥特曼的开端，开创了玩具联动的新模式。",
        skills: ["银河交叉射线", "银河闪电击", "银河慰藉", "银河特别光线", "银河维克特利光线"],
        stats: { power: 84, speed: 80, technique: 82, defense: 78, energy: 86, intelligence: 80 },
        rating: 4
    },
    {
        id: 14,
        name: "欧布奥特曼",
        nameEn: "Ultraman Orb",
        era: "new-gen",
        year: 2016,
        height: "50m",
        weight: "5万吨",
        home: "O-50行星",
        humanHost: "红凯",
        color: "#FF1744",
        colorSecondary: "#AA00FF",
        icon: "🔮",
        image: "images/ultraman_14.jpg",
        transformItem: "欧布圣剑",
        timeLimit: "3分钟",
        description: "在O-50行星山顶获得变身力量的流浪战士，人间体红凯是一位性格洒脱的旅人。欧布奥特曼可以通过两位前辈奥特曼的力量卡片融合变身，拥有重光、爆炎、疾风、暗黑等多种融合形态，是融合变身的先驱者。",
        skills: ["欧布至高圣剑", "欧布原始光线", "斯特比姆炸弹", "飓风斯派修姆", "暗黑Z修姆光线"],
        stats: { power: 86, speed: 78, technique: 86, defense: 76, energy: 88, intelligence: 82 },
        rating: 4.5
    },
    {
        id: 15,
        name: "捷德奥特曼",
        nameEn: "Ultraman Geed",
        era: "new-gen",
        year: 2017,
        height: "51m",
        weight: "4万1千吨",
        home: "地球",
        humanHost: "朝仓陆",
        color: "#2979FF",
        colorSecondary: "#FF1744",
        icon: "🧬",
        image: "images/ultraman_15.jpg",
        transformItem: "捷德升华器",
        timeLimit: "3分钟",
        description: "贝利亚奥特曼的儿子，却在人类朝仓陆的体内觉醒了正义之心。捷德的名字是'基因'的回文，象征着他与命运的抗争。从继承黑暗血统到选择光明之路，捷德的故事关于'定义自己的不是出身，而是选择'。",
        skills: ["十字冲击波", "毁灭爆裂", "冲击增幅", "扭曲光线", "皇家终结"],
        stats: { power: 84, speed: 80, technique: 80, defense: 74, energy: 82, intelligence: 82 },
        rating: 4
    },
    {
        id: 16,
        name: "罗布奥特曼",
        nameEn: "Ultraman R/B",
        era: "new-gen",
        year: 2018,
        height: "50m",
        weight: "4万4千吨",
        home: "O-50行星",
        humanHost: "凑活海 / 凕勇海",
        color: "#FF1744",
        colorSecondary: "#2979FF",
        icon: "🔥💧",
        image: "images/ultraman_16.jpg",
        transformItem: "罗布回旋器",
        timeLimit: "3分钟",
        description: "一对兄弟奥特曼——罗索（火）和布鲁（水），可以合体为罗布奥特曼。兄弟俩继承了母亲的爱之力，以家庭羁绊为核心对抗黑暗。这是系列中最注重家庭主题的作品，温馨日常与热血战斗交织。",
        skills: ["罗索火焰射线", "布鲁水之射线", "罗布光线", "真·罗布光线", "兄弟爆裂"],
        stats: { power: 82, speed: 78, technique: 78, defense: 76, energy: 80, intelligence: 76 },
        rating: 3.5
    },
    {
        id: 17,
        name: "泽塔奥特曼",
        nameEn: "Ultraman Z",
        era: "reiwa",
        year: 2020,
        height: "52m",
        weight: "3万3千吨",
        home: "M78星云光之国",
        humanHost: "遥辉",
        color: "#2979FF",
        colorSecondary: "#FF1744",
        icon: "🌀",
        image: "images/ultraman_17.jpg",
        transformItem: "泽塔升华器",
        timeLimit: "3分钟",
        description: "赛罗奥特曼的弟子，为了追踪怪兽勋章来到地球。泽塔性格认真但有些笨拙，通过借用前辈力量变身——阿尔法装甲、贝塔冲击、伽马未来和德尔塔天爪四种形态。他的口头禅'俺はゼット！'深入人心，剧集质量广受好评。",
        skills: ["泽斯帝姆光线", "泽塔冲击", "伽马幻影", "德尔塔终焉斩击", "泽塔永恒射线"],
        stats: { power: 84, speed: 82, technique: 80, defense: 76, energy: 84, intelligence: 78 },
        rating: 5
    },
    {
        id: 18,
        name: "特利迦奥特曼",
        nameEn: "Ultraman Trigger",
        era: "reiwa",
        year: 2021,
        height: "53m",
        weight: "4万4千吨",
        home: "超古代地球",
        humanHost: "真中剑悟",
        color: "#2979FF",
        colorSecondary: "#FF1744",
        icon: "✨",
        image: "images/ultraman_18.jpg",
        transformItem: "闪耀环",
        timeLimit: "3分钟",
        description: "三千万年前超古代的光之巨人，迪迦奥特曼精神续作的主角。特利迦拥有复合型、强力型、空中型三种基础形态，以及永恒核心力量驱动的闪耀形态。人间体剑悟的信念是'微笑'，相信笑容的力量能照亮黑暗。",
        skills: ["哉佩利敖光线", "兰帕尔特光弹", "迪拉修姆光流", "闪耀哉佩利敖光线", "永恒核心射线"],
        stats: { power: 82, speed: 80, technique: 82, defense: 76, energy: 84, intelligence: 80 },
        rating: 4
    },
    {
        id: 19,
        name: "德凯奥特曼",
        nameEn: "Ultraman Decker",
        era: "reiwa",
        year: 2022,
        height: "55m",
        weight: "4万5千吨",
        home: "未知",
        humanHost: "明日见奏大",
        color: "#FF1744",
        colorSecondary: "#2979FF",
        icon: "🛡️",
        image: "images/ultraman_19.jpg",
        transformItem: "德凯闪光",
        timeLimit: "3分钟",
        description: "继承了戴拿奥特曼精神的战士，面对斯菲亚的威胁而觉醒。德凯拥有闪光型、强壮型和奇迹型三种形态，其世界观延续了戴娜的故事。人间体奏大是一名普通大学生，在危机中选择了挺身而出。",
        skills: ["塞尔邦达光线", "加尔奈特轰炸", "立波留姆光波", "德凯强力光线", "奇迹空间斩"],
        stats: { power: 80, speed: 80, technique: 82, defense: 74, energy: 82, intelligence: 78 },
        rating: 3.5
    },
    {
        id: 20,
        name: "布莱泽奥特曼",
        nameEn: "Ultraman Blazar",
        era: "reiwa",
        year: 2023,
        height: "48m",
        weight: "3万7千吨",
        home: "M421星云",
        humanHost: "比留间弦人",
        color: "#00BFA5",
        colorSecondary: "#2979FF",
        icon: "🦅",
        image: "images/ultraman_20.jpg",
        transformItem: "布莱泽手环",
        timeLimit: "3分钟",
        description: "来自M421星云的野生奥特曼，与地球防卫队队长比留间弦人意外合体。布莱泽拥有野兽般的直觉和战斗风格，与弦人之间的沟通障碍成为本作特色。他使用名为'辉'的武器，以独特的'臂甲'式战斗方式取胜。",
        skills: ["斯派修姆射线", "布莱泽光轮", "辉·斩击", "布莱泽光束", "螺旋光线"],
        stats: { power: 86, speed: 84, technique: 76, defense: 80, energy: 80, intelligence: 72 },
        rating: 4
    }
];

// 时间线数据
const timelineData = [
    { year: 1966, event: "初代奥特曼播出，特摄英雄新纪元开启", era: "昭和" },
    { year: 1967, event: "赛文奥特曼登场，深化科幻与社会议题", era: "昭和" },
    { year: 1971, event: "杰克奥特曼回归，奥特兄弟概念成形", era: "昭和" },
    { year: 1972, event: "艾斯奥特曼登场，双人合体变身", era: "昭和" },
    { year: 1973, event: "泰罗奥特曼，奥特家族血缘揭秘", era: "昭和" },
    { year: 1974, event: "雷欧奥特曼，修炼与悲壮的战士故事", era: "昭和" },
    { year: 1980, event: "爱迪奥特曼，昭和系最后的电视系列", era: "昭和" },
    { year: 1996, event: "迪迦奥特曼，平成系列开创，形态切换概念", era: "平成" },
    { year: 1997, event: "戴拿奥特曼，迪迦世界观延续", era: "平成" },
    { year: 1998, event: "盖亚奥特曼，地球意志与宇宙之争", era: "平成" },
    { year: 2001, event: "高斯奥特曼，慈爱与和平的主题", era: "平成" },
    { year: 2004, event: "奈克瑟斯奥特曼，最深沉暗黑的奥特曼", era: "平成" },
    { year: 2006, event: "梦比优斯奥特曼，40周年纪念，昭和回归", era: "平成" },
    { year: 2009, event: "赛罗奥特曼登场，新生代领路人诞生", era: "平成" },
    { year: 2013, event: "银河奥特曼，新生代系列开始", era: "新生代" },
    { year: 2016, event: "欧布奥特曼，融合变身概念开创", era: "新生代" },
    { year: 2017, event: "捷德奥特曼，贝利亚之子的正道抉择", era: "新生代" },
    { year: 2020, event: "泽塔奥特曼，令和系列口碑巅峰", era: "令和" },
    { year: 2021, event: "特利迦奥特曼，迪迦精神续作", era: "令和" },
    { year: 2023, event: "布莱泽奥特曼，野生系奥特曼登场", era: "令和" },
];
